<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>x86</PlatformTarget>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>0.1.0</Version>
    <FileVersion>0.1.0.0</FileVersion>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <ApplicationManifest>AppManifest.xml</ApplicationManifest>
    <ApplicationIcon>assets\SpeedScanManager.ico</ApplicationIcon>
    <DefaultItemExcludes>$(DefaultItemExcludes);installer\**</DefaultItemExcludes>
    <Company>VeridonNetzwerk</Company>
    <Product>SpeedScan Manager</Product>
    <Copyright>Copyright © 2024 VeridonNetzwerk</Copyright>
    <Description>Document scanning management application with TWAIN support</Description>
    <Trademark>SpeedScan Manager is a trademark of VeridonNetzwerk</Trademark>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NTwain" Version="3.7.6" />
    <PackageReference Include="PdfSharpCore" Version="1.3.65" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.1.0" />
    <PackageReference Include="Svg" Version="3.4.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="assets\SpeedScanManager_Logo.png" LogicalName="SpeedScanManager_Logo.png" />
    <EmbeddedResource Include="assets\SpeedScanManager_Text.png" LogicalName="SpeedScanManager_Text.png" />
    <EmbeddedResource Include="assets\github_logo.svg" LogicalName="github_logo.svg" />
    <EmbeddedResource Include="assets\discord_logo.svg" LogicalName="discord_logo.svg" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="assets\scanbutton.vbs" Link="scanbutton.vbs" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
